//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingTable
    {
        public string EntryNumber { get; set; }
        public string AccountNumber { get; set; }
        public string PaymentMonth { get; set; }
        public string Rate { get; set; }
        public string KWNumber { get; set; }
    }
}
