//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceTable
    {
        public string AccountNumber { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
    }
}
